confirmOnQuit: true
disableStartupPopups: true
gui:
  language: en
  portraitMode: never
  shortTimeFormat: 15:04
  timeFormat: 2006-01-02
notARepository: quit
update:
  method: never # handled by the package manager
